export default {
  pt: {
    headerSwitcher: {
      save: "Salvar",
      upToDate: "Já atualizado",
      load: "Load",
    },
    infoTable: {
      sendButton: "Enviar para o BD",
      group: "Grupo",
    },
    accountSelectionModal: {
      heading: "Selecione a conta desejada",
      label: "Contas disponíveis",
      primaryText: "Selecionar",
      secondaryText: "Cancelar",
      inputLabel1: "Contas",
    },
    modal: {
      heading: "Informações de conexão com Db2",
      label: "Instância e Tabela consultadas",
      primaryText: "Recarregar",
      secondaryText: "Salvar",
      selectAnOption: "Selecione uma opção",
      alert: "Por favor, selecione uma das instâncias listadas",
      inputLabel1: "Selecione a instância do Db2 desejada",
      inputLabel2: "Insira o título da tabela a ser consultada",
    },
    cognosModal: {
      heading: "Credenciais de uso do Cognos",
      label: "Instâncias consultadas",
      primaryText: "Recarregar",
      secondaryText: "Salvar",
      tab1: "Cognos",
      tab2: "Cloudant",
      tab3: "Db2",
      tab4: "Tabelas",
      selectAnOption: "Selecione uma opção",
      alert: "Por favor, selecione uma das instâncias listadas",
      inputLabel1: "Selecione a instância do Cognos desejada",
      inputLabel2: "Selecione a instância do Cloudant desejada",
      inputLabel3: "Insira a database do Cloudant desejada",
      inputLabel4: "Selecione a instância do Db2 desejada",
      inputLabel5: "Insira o link do módulo xsd",
      inputLabel6: "Insira o driver Jdbc",
      inputLabel7: "Tabela de logs",
      inputLabel8: "Tabela de conversas",
      inputLabel9: "Tabela de telefonemas",
      inputLabel10: "Tabela de variáveis de contexto",
      inputLabel11: "Tabela de caminhos de conversa",
      inputLabel12: "Tabela de visão geral",
      inputLabel13: "Tabela de distribuição de classes",
      inputLabel14: "Tabela de precisão @k",
      inputLabel15: "Tabela de acurácia de classes",
      inputLabel16: "Tabela de intenções confundidas",
      inputLabel17: "Tabela de acurácia vs cobertura",
    },
    saveModal: {
      heading:
        "Insira o nome que deseja dar ao dashboard. Este será automaticamente configurado como Dashboard default",
      label: "Salvar Dashboard no Cloudant",
      primaryText: "Salvar",
      secondaryText: "Cancelar",
      inputLabel1: "Nome (ID) do Dashboard",
    },
    loadModal: {
      heading:
        "Insira o nome do dashboard que deseja buscar. Este será automaticamente configurado como Dashboard default",
      label: "Buscar Dashboard no Cloudant",
      primaryText: "Buscar",
      secondaryText: "Cancelar",
      inputLabel1: "Nome (ID) do Dashboard",
    },
    modalHelp: {
      heading: "Ajuda",
      text: "Esta tabela exibe a troca de mensagens entre cliente e Assistente, destacando qual foi a intent compreendida pelo assistente na mensagem recebida. Com estas informações, o curador pode avaliar o desempenho do assistente no nível de mensagem.",
    },
    cognosModalHelp: {
      heading: "Ajuda",
      text: "Esta página exibe um dashboard interativo que apresenta métricas para auxiliar o processo de curadoria do assitente.",
    },
    modalWarning: {
      heading: "Aviso",
      text: "Não foi possível realizar a conexão com a base de dados através dos dados fornecidos. Por favor verifique as informações inseridas e tente novamente.",
      caption: "",
    },
    standardDashboardModal: {
      heading: "Aviso",
      text: "Inicializando Dashboard Padrão.",
      caption: "",
    },
    modalSuccess: {
      heading: "Sucesso!",
      text: "Conexão realizada com sucesso.",
      caption: "",
    },
    tabs: {
      itensPerPage: "Itens por página",
    },
  },
  es: {
    headerSwitcher: {
      save: "Guardar",
      upToDate: "Já actualizado",
      load: "Cargar",
    },
    infoTable: {
      sendButton: "Enviar a BD",
      group: "Grupo",
    },
    accountSelectionModal: {
      heading: "Seleccione la cuenta deseada",
      label: "Cuentas disponibles",
      primaryText: "Seleccione",
      secondaryText: "Cancelar",
      inputLabel1: "Cuentas",
    },
    modal: {
      heading: "Información de conexión de Db2",
      label: "Instancia y Tabla consultada",
      primaryText: "Recargar",
      secondaryText: "Guardar",
      selectAnOption: "Seleccione una opción",
      alert: "Seleccione una de las instancias enumeradas",
      inputLabel1: "Seleccione la instancia de Db2 deseada",
      inputLabel2: "Introduzca el título de la tabla a consultar",
    },
    cognosModal: {
      heading: "Credenciales de uso de Cognos",
      label: "Instancias consultadas",
      primaryText: "Recargar",
      secondaryText: "Guardar",
      tab1: "Cognos",
      tab2: "Cloudant",
      tab3: "Db2",
      tab4: "Tablas",
      selectAnOption: "Seleccione una opción",
      alert: "Seleccione una de las instancias enumeradas",
      inputLabel1: "Seleccione la instancia de Cognos deseada",
      inputLabel2: "Seleccione la instancia de Cloudant deseada",
      inputLabel3: "Inserte la base de datos Cloudant deseada",
      inputLabel4: "Seleccione la instancia de Db2 deseada",
      inputLabel5: "Inserte el enlace del módulo xsd",
      inputLabel6: "Inserte el driver Jdbc",
      inputLabel7: "Tabla de registros",
      inputLabel8: "Tabla de conversaciónes",
      inputLabel9: "Tabla de llamadas telefonicas",
      inputLabel10: "Tabla de variables de contexto",
      inputLabel11: "Tabla de ruta de conversación",
      inputLabel12: "Tabla de resumen",
      inputLabel13: "Tabla de distribución de clases",
      inputLabel14: "Tabla de precisión @k",
      inputLabel15: "Tabla de precisión de clase",
      inputLabel16: "Tabla de intenciones confusas",
      inputLabel17: "Tabla de precisión versus cobertura",
    },
    saveModal: {
      heading:
        "Ingrese el nombre que desea darle al Dashboard. Esto se establecerá automáticamente como el Dashboard default",
      label: "Guardar Dashboard en Cloudant",
      primaryText: "Salvar",
      secondaryText: "Cancelar",
      inputLabel1: "Nombre (ID) del Dashboard",
    },
    loadModal: {
      heading:
        "Ingrese el nombre del Dashboard que desea buscar. Esto se establecerá automáticamente como el Dashboard default",
      label: "Busca de Dashboard en Cloudant",
      primaryText: "Buscar",
      secondaryText: "Cancelar",
      inputLabel1: "Nombre (ID) del Dashboard",
    },
    modalHelp: {
      heading: "Ayuda",
      text: "Esta tabla muestra el intercambio de mensajes entre el cliente y el Asistente, destacando qué intención entendió el asistente en el mensaje recibido. Con esta información, el curador puede evaluar el desempeño del asistente a nivel del mensaje.",
    },
    cognosModalHelp: {
      heading: "Ayuda",
      text: "Esta página muestra un tablero interactivo que presenta métricas para respaldar el proceso de curación del asistente.",
    },
    modalWarning: {
      heading: "Error!",
      text: "No fue posible conectarse a la base de datos utilizando los datos proporcionados. Verifique la información ingresada y vuelva a intentarlo.",
      caption: "",
    },
    standardDashboardModal: {
      heading: "Aviso",
      text: "Inicializando el Dashboard predeterminado.",
      caption: "",
    },
    modalSuccess: {
      heading: "Éxito!",
      text: "Conexión exitosa.",
      caption: "",
    },
    tabs: {
      itensPerPage: "Artículos por página",
    },
  },
  en: {
    headerSwitcher: {
      save: "Save",
      upToDate: "Up to date",
      load: "Load",
    },
    infoTable: {
      sendButton: "Send to DB",
      group: "Group",
    },
    accountSelectionModal: {
      heading: "Select the desired account",
      label: "Available accounts",
      primaryText: "Select",
      secondaryText: "Cancel",
      inputLabel1: "Accounts",
    },
    modal: {
      heading: "Db2 conection information",
      label: "Instance and Table to be consulted",
      primaryText: "Reload",
      secondaryText: "Save",
      selectAnOption: "Select an option",
      alert: "Please select one of the listed instances",
      inputLabel1: "Select the desired Db2 instance",
      inputLabel2: "Enter the title of the table to be queried",
    },
    cognosModal: {
      heading: "Cognos credentials",
      label: "Consulted Instances",
      primaryText: "Reload",
      secondaryText: "Save",
      tab1: "Cognos",
      tab2: "Cloudant",
      tab3: "Db2",
      tab4: "Tables",
      selectAnOption: "Select an option",
      alert: "Please select one of the listed instances",
      inputLabel1: "Select the desired Cognos instance",
      inputLabel2: "Select the desired Cloudant instance",
      inputLabel3: "Enter the desired Cloudant database",
      inputLabel4: "Select the desired Db2 instance",
      inputLabel5: "Enter the xsd module link",
      inputLabel6: "Enter the Jdbc driver",
      inputLabel7: "Logs table",
      inputLabel8: "Conversations table",
      inputLabel9: "Calls table",
      inputLabel10: "Context variables table",
      inputLabel11: "Conversation path table",
      inputLabel12: "Overview table",
      inputLabel13: "Class Distribution table",
      inputLabel14: "Precision @k table",
      inputLabel15: "Class accuracy table",
      inputLabel16: "Pair wise class errors table",
      inputLabel17: "Accuracy vs coverage table",
    },
    saveModal: {
      heading:
        "Enter the name you want to give the Dashboard. This will automatically be set as the default Dashboard",
      label: "Save Dashboard in Cloudant",
      primaryText: "Save",
      secondaryText: "Cancel",
      inputLabel1: "Dashboard name (ID)",
    },
    loadModal: {
      heading:
        "Enter the name of the Dashboard you want to search. This will automatically be set as the default Dashboard",
      label: "Search Dashboard in Cloudant",
      primaryText: "Search",
      secondaryText: "Cancel",
      inputLabel1: "Dashboard name (ID)",
    },
    modalHelp: {
      heading: "Help",
      text: "This table displays the exchange of messages between client and Assistant, highlighting what intent was understood by the assistant in the received message. With this information, the curator can assess the assistant's performance at the message level.",
    },
    cognosModalHelp: {
      heading: "Help",
      text: "This page displays an interactive dashboard that presents metrics to support the Assistant curation process.",
    },
    modalWarning: {
      heading: "Error!",
      text: "It was not possible to connect through the supplied data. Please check the information and try again.",
      caption: "",
    },
    standardDashboardModal: {
      heading: "Warning",
      text: "Initializing default Dashboard.",
      caption: "",
    },
    modalSuccess: {
      heading: "Success!",
      text: "Successfully connected.",
      caption: "",
    },
    tabs: {
      itensPerPage: "Items per page",
    },
  },
};
